### PR TITLE
Spec 0.2

### PR DESCRIPTION
**Pull request by xamde**
Ok, here is the DRAFT for a 0.2 OCIF spec. The existing README.md is left untouched.
We could also continue  to work in a "spec-0.2" branch, until it can replace main in a consistent state.

### CODE REVIEW

**Comment by devhelpr** [comment]
some notes/questions:
- resources could be a map, because nodes reference them by id, a map seams more logical to me
- regarding rotation : if the rotation is around the center of the node.. how can the rotation center be the positioned point, i.e. top-left? 
- I am not sure about the custom styling of the document , I had to change it to make the spec readable in my vs.code markdown preview

**Comment by devhelpr** [comment]
question for the next meetup:
- how do we define the order of the nodes ? tldraw has an index property which works like a [fractional index](https://observablehq.com/@dgreensp/implementing-fractional-indexing) if am not mistaken. Is this also something we want?

**Comment by xamde** [comment]
I'll abandon this PR and create a new one, for spec-0.2.1, based on a branch in this repo

**Comment by jessmartin** [comment]
Closing per @xamde's recommendation.

**Pull request closed without merging**
